name: Spinnaker Webhook
description: initiates a deploy on spinnaker
inputs:
  token:
    description: |
      the auth token. this can also be passed in with
      the env SPINNAKER_WEBHOOK_TOKEN.
  host:
    description: |
      the host of the spinnaker. this can also be passed
      in with the env SPINNAKER_WEBHOOK_HOST.
  name:
    description: |
      the webhook name. this can also be passed in with
      the env SPINNAKER_WEBHOOK_NAME.
  sha:
    description: |
      what sha to pass to spinnaker to deploy. if this
      is not specified, it will use SPINNAKER_WEBHOOK_SHA or GITHUB_SHA
  extraParams:
    default: '{}'
    description: |
      pass in a json object to add parameters to the 
      webhook call. it will also check the env SPINNAKER_WEBHOOK_EXTRA_PARAMS
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/spinnaker-webhook.sh
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_HOST: ${{ inputs.host }}
        INPUT_NAME: ${{ inputs.name }}
        INPUT_SHA: ${{ inputs.sha }}
        INPUT_EXTRA_PARAMS: ${{ inputs.extraParams }}
